### ISSUE TITLE
Fail to load gist-embed

### ISSUE THREAD

**Issue by jaredready** [pasupulaphani/angular-gist-embed#2]
This appears to try to load `//cdnjs.cloudflare.com/ajax/libs/gist-embed/2.0/gist-embed.min.js`, but fails. 
Loading `http://cdnjs.cloudflare.com/ajax/libs/gist-embed/2.0/gist-embed.min.js` succeeds. Is this just my environment?

Ubuntu 14.04
NW.js 0.12

**Comment by abhijeetpathak** [comment]
Browser uses current protocol (http, https) automatically.
Seems like an environment issue.
